<?php

namespace ContainerU2UiwcN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8WpPsiaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8WpPsia' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.iOBMqcQ.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\AdminController::updateStatus' => ['privates', '.service_locator.hx0ySSg.App\\Controller\\AdminController::updateStatus()', 'getAdminControllerupdateStatusService', true],
            'App\\Controller\\Api\\ProductApiController::list' => ['privates', '.service_locator.dcfjolD.App\\Controller\\Api\\ProductApiController::list()', 'getProductApiControllerlistService', true],
            'App\\Controller\\Api\\ProductApiController::detail' => ['privates', '.service_locator.dcfjolD.App\\Controller\\Api\\ProductApiController::detail()', 'getProductApiControllerdetailService', true],
            'App\\Controller\\Api\\ProductApiController::makeOrder' => ['privates', '.service_locator.7ophXXY.App\\Controller\\Api\\ProductApiController::makeOrder()', 'getProductApiControllermakeOrderService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.aYn6tmH.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.aYn6tmH.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.aYn6tmH.App\\Controller\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\CheckoutController::index' => ['privates', '.service_locator.bXyqoOH.App\\Controller\\CheckoutController::index()', 'getCheckoutControllerindexService', true],
            'App\\Controller\\CheckoutController::success' => ['privates', '.service_locator.wsg9C44.App\\Controller\\CheckoutController::success()', 'getCheckoutControllersuccessService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.iOBMqcQ.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\AdminController:updateStatus' => ['privates', '.service_locator.hx0ySSg.App\\Controller\\AdminController::updateStatus()', 'getAdminControllerupdateStatusService', true],
            'App\\Controller\\Api\\ProductApiController:list' => ['privates', '.service_locator.dcfjolD.App\\Controller\\Api\\ProductApiController::list()', 'getProductApiControllerlistService', true],
            'App\\Controller\\Api\\ProductApiController:detail' => ['privates', '.service_locator.dcfjolD.App\\Controller\\Api\\ProductApiController::detail()', 'getProductApiControllerdetailService', true],
            'App\\Controller\\Api\\ProductApiController:makeOrder' => ['privates', '.service_locator.7ophXXY.App\\Controller\\Api\\ProductApiController::makeOrder()', 'getProductApiControllermakeOrderService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.aYn6tmH.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.aYn6tmH.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.aYn6tmH.App\\Controller\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\CheckoutController:index' => ['privates', '.service_locator.bXyqoOH.App\\Controller\\CheckoutController::index()', 'getCheckoutControllerindexService', true],
            'App\\Controller\\CheckoutController:success' => ['privates', '.service_locator.wsg9C44.App\\Controller\\CheckoutController::success()', 'getCheckoutControllersuccessService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::updateStatus' => '?',
            'App\\Controller\\Api\\ProductApiController::list' => '?',
            'App\\Controller\\Api\\ProductApiController::detail' => '?',
            'App\\Controller\\Api\\ProductApiController::makeOrder' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\CheckoutController::index' => '?',
            'App\\Controller\\CheckoutController::success' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:updateStatus' => '?',
            'App\\Controller\\Api\\ProductApiController:list' => '?',
            'App\\Controller\\Api\\ProductApiController:detail' => '?',
            'App\\Controller\\Api\\ProductApiController:makeOrder' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\CheckoutController:index' => '?',
            'App\\Controller\\CheckoutController:success' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.8WpPsia'])) {
            return $container->privates['.service_locator.8WpPsia'];
        }

        return $container->privates['.service_locator.8WpPsia'] = $instance;
    }
}
