<?php

namespace ContainerU2UiwcN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerupdateStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hx0ySSg.App\Controller\AdminController::updateStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.hx0ySSg.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.hx0ySSg": it needs an instance of "App\\Entity\\Order" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'order' => 'App\\Entity\\Order',
            'entityManager' => '?',
            'messageBus' => '?',
        ]))->withContext('App\\Controller\\AdminController::updateStatus()', $container);

        if (isset($container->privates['.service_locator.hx0ySSg.App\\Controller\\AdminController::updateStatus()'])) {
            return $container->privates['.service_locator.hx0ySSg.App\\Controller\\AdminController::updateStatus()'];
        }

        return $container->privates['.service_locator.hx0ySSg.App\\Controller\\AdminController::updateStatus()'] = $instance;
    }
}
