<?php

namespace ContainerU2UiwcN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bXyqoOH.App\Controller\CheckoutController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'requestStack' => '?',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CheckoutController::index()', $container);

        if (isset($container->privates['.service_locator.bXyqoOH.App\\Controller\\CheckoutController::index()'])) {
            return $container->privates['.service_locator.bXyqoOH.App\\Controller\\CheckoutController::index()'];
        }

        return $container->privates['.service_locator.bXyqoOH.App\\Controller\\CheckoutController::index()'] = $instance;
    }
}
