<?php

namespace ContainerU2UiwcN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hx0ySSg.App\Entity\Order' shared service.
     *
     * @return \App\Entity\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hx0ySSg": it needs an instance of "App\\Entity\\Order" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
