<?php

namespace ContainerUtWWIM1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCustomAuthenticatorService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Security\AppCustomAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppCustomAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppCustomAuthenticator'] = new \App\Security\AppCustomAuthenticator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
