<?php

namespace ContainerUtWWIM1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_AsyncService extends App_KernelDevContainer
{
    /*
     * Gets the private 'messenger.transport.async' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\Messenger\Transport\TransportFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['messenger.transport.sync.factory'] ?? $container->load('getMessenger_Transport_Sync_FactoryService'));
            yield 1 => ($container->privates['messenger.transport.in_memory.factory'] ?? $container->load('getMessenger_Transport_InMemory_FactoryService'));
            yield 2 => ($container->privates['messenger.transport.doctrine.factory'] ?? $container->load('getMessenger_Transport_Doctrine_FactoryService'));
        }, 3)))->createTransport('doctrine://default', ['transport_name' => 'async'], new \Symfony\Component\Messenger\Transport\Serialization\SigningSerializer(new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer(), \Symfony\Component\String\LazyString::fromCallable(#[\Closure(name: '.messenger.signing_serializer.signing_key', class: 'string')] fn () => ($container->privates['.messenger.signing_serializer.signing_key'] ?? $container->load('get_Messenger_SigningSerializer_SigningKeyService'))), ['Symfony\\Component\\Process\\Messenger\\RunProcessMessage', 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage']));

        if (isset($container->privates['messenger.transport.async'])) {
            return $container->privates['messenger.transport.async'];
        }

        return $container->privates['messenger.transport.async'] = $instance;
    }
}
