<?php

namespace ContainerUtWWIM1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Controller_ScalarService extends App_KernelDevContainer
{
    /*
     * Gets the public 'nelmio_api_doc.controller.scalar' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Controller\SwaggerUiController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['nelmio_api_doc.controller.scalar'] = new \Nelmio\ApiDocBundle\Controller\SwaggerUiController(($container->services['nelmio_api_doc.render_docs'] ?? $container->load('getNelmioApiDoc_RenderDocsService')), 'scalar');
    }
}
