<?php

namespace ContainerUtWWIM1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductApiControllermakeOrderService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.7ophXXY.App\Controller\Api\ProductApiController::makeOrder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'entityManager' => '?',
            'messageBus' => '?',
        ]))->withContext('App\\Controller\\Api\\ProductApiController::makeOrder()', $container);

        if (isset($container->privates['.service_locator.7ophXXY.App\\Controller\\Api\\ProductApiController::makeOrder()'])) {
            return $container->privates['.service_locator.7ophXXY.App\\Controller\\Api\\ProductApiController::makeOrder()'];
        }

        return $container->privates['.service_locator.7ophXXY.App\\Controller\\Api\\ProductApiController::makeOrder()'] = $instance;
    }
}
