<?php

namespace ContainerUtWWIM1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductApiControllerlistService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.dcfjolD.App\Controller\Api\ProductApiController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dcfjolD.App\\Controller\\Api\\ProductApiController::list()'] = ($container->privates['.service_locator.dcfjolD'] ?? $container->load('get_ServiceLocator_DcfjolDService'))->withContext('App\\Controller\\Api\\ProductApiController::list()', $container);
    }
}
