<?php

namespace ContainerU6hFtsL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RIxl4HGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RIxl4HG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'messenger.transport.async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
        ], [
            'async' => '?',
            'messenger.transport.async' => '?',
        ]);

        if (isset($container->privates['.service_locator.RIxl4HG'])) {
            return $container->privates['.service_locator.RIxl4HG'];
        }

        return $container->privates['.service_locator.RIxl4HG'] = $instance;
    }
}
