<?php

namespace ContainerU6hFtsL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllersuccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2QpohGd.App\Controller\CheckoutController::success()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2QpohGd.App\\Controller\\CheckoutController::success()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.2QpohGd.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.2QpohGd": it needs an instance of "App\\Entity\\Order" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'order' => 'App\\Entity\\Order',
        ]))->withContext('App\\Controller\\CheckoutController::success()', $container);
    }
}
