<?php

namespace ContainerU6hFtsL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_TypeDescriber_TemplateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.type_describer.template' shared service.
     *
     * @return \Nelmio\ApiDocBundle\TypeDescriber\TemplateDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'TypeDescriber'.\DIRECTORY_SEPARATOR.'TypeDescriberInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'TypeDescriber'.\DIRECTORY_SEPARATOR.'TypeDescriberAwareInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'TypeDescriber'.\DIRECTORY_SEPARATOR.'TypeDescriberAwareTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'TypeDescriber'.\DIRECTORY_SEPARATOR.'TemplateDescriber.php';

        $a = ($container->privates['nelmio_api_doc.type_describer.chain'] ?? $container->load('getNelmioApiDoc_TypeDescriber_ChainService'));

        if (isset($container->privates['nelmio_api_doc.type_describer.template'])) {
            return $container->privates['nelmio_api_doc.type_describer.template'];
        }

        $instance = new \Nelmio\ApiDocBundle\TypeDescriber\TemplateDescriber($a);

        if (isset($container->privates['nelmio_api_doc.type_describer.template'])) {
            return $container->privates['nelmio_api_doc.type_describer.template'];
        }

        return $container->privates['nelmio_api_doc.type_describer.template'] = $instance;
    }
}
