<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Order__CLASSMETADATA__' => 0,
'App__Entity__Product__CLASSMETADATA__' => 1,
'App__Entity__User__CLASSMETADATA__' => 2,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator')),
        clone ($p['Symfony\\Component\\Uid\\Factory\\UuidFactory'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Uid\\Factory\\UuidFactory')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Order',
            ],
            'customGeneratorDefinition' => [
                [
                    'class' => 'doctrine.uuid_generator',
                ],
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\OrderRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                7,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'clientEmail' => $o[2],
                    'status' => $o[3],
                    'totalPrice' => $o[4],
                    'stripeSessionId' => $o[5],
                    'createdAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'client_email' => 'clientEmail',
                    'status' => 'status',
                    'total_price' => 'totalPrice',
                    'stripe_session_id' => 'stripeSessionId',
                    'created_at' => 'createdAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'clientEmail' => 'client_email',
                    'status' => 'status',
                    'totalPrice' => 'total_price',
                    'stripeSessionId' => 'stripe_session_id',
                    'createdAt' => 'created_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'order',
                    'quoted' => true,
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\Order',
            ],
            'id' => [
                1 => true,
            ],
            'unique' => [
                1 => true,
            ],
            'type' => [
                1 => 'uuid',
                'string',
                'string',
                'integer',
                'string',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'clientEmail',
                'status',
                'totalPrice',
                'stripeSessionId',
                'createdAt',
            ],
            'columnName' => [
                1 => 'id',
                'client_email',
                'status',
                'total_price',
                'stripe_session_id',
                'created_at',
            ],
            'length' => [
                2 => 255,
                255,
                5 => 255,
            ],
            'nullable' => [
                5 => true,
            ],
        ],
        'Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator' => [
            'protoFactory' => [
                7 => $o[8],
            ],
            'factory' => [
                7 => $o[8],
            ],
        ],
        'Symfony\\Component\\Uid\\Factory\\UuidFactory' => [
            'defaultClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'timeBasedClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'nameBasedClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV5',
            ],
            'randomBasedClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV4',
            ],
            'timeBasedNode' => [
                8 => null,
            ],
            'nameBasedNamespace' => [
                8 => null,
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator')),
        clone ($p['Symfony\\Component\\Uid\\Factory\\UuidFactory'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Uid\\Factory\\UuidFactory')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Product',
            ],
            'customGeneratorDefinition' => [
                [
                    'class' => 'doctrine.uuid_generator',
                ],
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ProductRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                7,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'description' => $o[3],
                    'price' => $o[4],
                    'stock' => $o[5],
                    'image' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'price' => 'price',
                    'stock' => 'stock',
                    'image' => 'image',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'price' => 'price',
                    'stock' => 'stock',
                    'image' => 'image',
                ],
            ],
            'table' => [
                [
                    'name' => 'product',
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\Product',
            ],
            'id' => [
                1 => true,
            ],
            'unique' => [
                1 => true,
            ],
            'type' => [
                1 => 'uuid',
                'string',
                'text',
                'integer',
                'integer',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'description',
                'price',
                'stock',
                'image',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'description',
                'price',
                'stock',
                'image',
            ],
            'length' => [
                2 => 255,
                6 => 255,
            ],
            'nullable' => [
                6 => true,
            ],
        ],
        'Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator' => [
            'protoFactory' => [
                7 => $o[8],
            ],
            'factory' => [
                7 => $o[8],
            ],
        ],
        'Symfony\\Component\\Uid\\Factory\\UuidFactory' => [
            'defaultClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'timeBasedClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'nameBasedClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV5',
            ],
            'randomBasedClass' => [
                8 => 'Symfony\\Component\\Uid\\UuidV4',
            ],
            'timeBasedNode' => [
                8 => null,
            ],
            'nameBasedNamespace' => [
                8 => null,
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator')),
        clone ($p['Symfony\\Component\\Uid\\Factory\\UuidFactory'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Uid\\Factory\\UuidFactory')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customGeneratorDefinition' => [
                [
                    'class' => 'doctrine.uuid_generator',
                ],
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                7,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                    'uniqueConstraints' => [
                        'UNIQ_IDENTIFIER_EMAIL' => [
                            'fields' => [
                                'email',
                            ],
                        ],
                    ],
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'unique' => [
                1 => true,
            ],
            'type' => [
                1 => 'uuid',
                'string',
                'json',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
            ],
            'columnName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
            ],
            'length' => [
                2 => 180,
            ],
        ],
        'Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator' => [
            'protoFactory' => [
                5 => $o[6],
            ],
            'factory' => [
                5 => $o[6],
            ],
        ],
        'Symfony\\Component\\Uid\\Factory\\UuidFactory' => [
            'defaultClass' => [
                6 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'timeBasedClass' => [
                6 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'nameBasedClass' => [
                6 => 'Symfony\\Component\\Uid\\UuidV5',
            ],
            'randomBasedClass' => [
                6 => 'Symfony\\Component\\Uid\\UuidV4',
            ],
            'timeBasedNode' => [
                6 => null,
            ],
            'nameBasedNamespace' => [
                6 => null,
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
