<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtWWIM1\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtWWIM1/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerUtWWIM1.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerUtWWIM1\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerUtWWIM1\App_KernelDevContainer([
    'container.build_hash' => 'UtWWIM1',
    'container.build_id' => '0030398d',
    'container.build_time' => 1778066654,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtWWIM1');
