<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6hFtsL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6hFtsL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU6hFtsL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU6hFtsL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU6hFtsL\App_KernelDevDebugContainer([
    'container.build_hash' => 'U6hFtsL',
    'container.build_id' => '23953b16',
    'container.build_time' => 1778068286,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6hFtsL');
