<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'admin_order_status' => [['id', 'status'], ['_controller' => 'App\\Controller\\AdminController::updateStatus'], [], [['variable', '/', '[^/]++', 'status', true], ['text', '/status'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/order']], [], [], []],
    'api_products_list' => [[], ['_controller' => 'App\\Controller\\Api\\ProductApiController::list'], [], [['text', '/api/products']], [], [], []],
    'api_product_detail' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProductApiController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'api_make_order' => [[], ['_controller' => 'App\\Controller\\Api\\ProductApiController::makeOrder'], [], [['text', '/api/order']], [], [], []],
    'app_cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart']], [], [], []],
    'cart_add' => [['id'], ['_controller' => 'App\\Controller\\CartController::add'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/add']], [], [], []],
    'cart_remove' => [['id'], ['_controller' => 'App\\Controller\\CartController::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/remove']], [], [], []],
    'app_checkout' => [[], ['_controller' => 'App\\Controller\\CheckoutController::index'], [], [['text', '/checkout']], [], [], []],
    'app_checkout_success' => [['id'], ['_controller' => 'App\\Controller\\CheckoutController::success'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/checkout/success']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\AdminController::index' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'App\Controller\AdminController::updateStatus' => [['id', 'status'], ['_controller' => 'App\\Controller\\AdminController::updateStatus'], [], [['variable', '/', '[^/]++', 'status', true], ['text', '/status'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/order']], [], [], []],
    'App\Controller\Api\ProductApiController::list' => [[], ['_controller' => 'App\\Controller\\Api\\ProductApiController::list'], [], [['text', '/api/products']], [], [], []],
    'App\Controller\Api\ProductApiController::detail' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProductApiController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'App\Controller\Api\ProductApiController::makeOrder' => [[], ['_controller' => 'App\\Controller\\Api\\ProductApiController::makeOrder'], [], [['text', '/api/order']], [], [], []],
    'App\Controller\CartController::index' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart']], [], [], []],
    'App\Controller\CartController::add' => [['id'], ['_controller' => 'App\\Controller\\CartController::add'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/add']], [], [], []],
    'App\Controller\CartController::remove' => [['id'], ['_controller' => 'App\\Controller\\CartController::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/remove']], [], [], []],
    'App\Controller\CheckoutController::index' => [[], ['_controller' => 'App\\Controller\\CheckoutController::index'], [], [['text', '/checkout']], [], [], []],
    'App\Controller\CheckoutController::success' => [['id'], ['_controller' => 'App\\Controller\\CheckoutController::success'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/checkout/success']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
